### PR TITLE
FISH-6772 javaee8 to jakartaee10

### PR DESCRIPTION
**Pull request by luiseufrasio**

### CODE REVIEW

**Review by jGauravGupta — CHANGES_REQUESTED** [review]
Overriding the project or file, should not be replaced with random number prefix.

**Comment by aubi** [comment]
I tried Payara Refactor -> Transform to Jakarta EE 10, both to new directory and to the same directory. It works well for me - Linux, OpenJDK 17

**Review by aubi — APPROVED** [review]
Works for me

**Comment by breakponchito** [comment]
Works for me also

**Pull request merged**
