### PR TITLE
EP-44 Same key startup JVM Options are overwritten

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Comment by jGauravGupta** [comment]
Hi @CarlosMOGoncalves,

Can you review the PR and check attached artifacts to reproduce the issue?

[payara-tools-repository-1.0.0.201909101237.zip](https://github.com/payara/ecosystem-eclipse-plugin/files/3594372/payara-tools-repository-1.0.0.201909101237.zip)

**Comment by CarlosMOGoncalves** [comment]
Hello @jGauravGupta , sorry for the time I took. Only now I am returning from vacation.

I checked the PR, applied it to my code and debugged it. It works perfectly fine!

Indeed, it does not overwrite the options with the same name (multiple --add-xxx) and it naturally preserves the same behaviour that allows it to trick the ProcessImpl into sending these arguments to the java process. It works perfectly for my use case and I feel that this solution should somehow be replicated to Payara Server (as in [here](https://github.com/payara/Payara/issues/4187)).

However, I feel this is likely not enough, because sadly "--add-xxx" are not the only kind of options that obey the same possible format. There are others, like "--limit-modules" or "--patch-module" and maybe some other long options (I did not make an exhaustive search).

I have checked [here the possible options](https://docs.oracle.com/javase/9/tools/java.htm#JSWOR624).

Should I approve it anyway or would you rather try to include also these other options? It is likely that someone will have this problem as soon as people start migrating to JDK11 in the next releases of Payara.

**Comment by jGauravGupta** [comment]
Thanks @CarlosMOGoncalves, for the feedback.

**Comment by CarlosMOGoncalves** [comment]
Well, I think that really does it. Thanks @jGauravGupta!

**Pull request merged**
