### PR TITLE
Release Eclipse plugin v1.0.1

### PR DESCRIPTION
**Pull request by jGauravGupta**
Attached the build package and update link for testing:

Go to Eclipse IDE > Help > Install new Software > Available Panel

**Package installer:**
[payara-tools-repository-1.0.1.201912202010.zip](https://github.com/payara/ecosystem-eclipse-plugin/files/3988771/payara-tools-repository-1.0.1.201912202010.zip)
Manually drop the package on Available Software panel to install and test.

**Alpha Update link installer:**
https://raw.githubusercontent.com/jGauravGupta/Payara_PatchedProjects/ECOSYS-82/payaratools/oxygen/alpha
Add the link to `Work with` field in Available Software panel to install and test.

Related PR: https://github.com/payara/Payara_PatchedProjects/pull/287

### CODE REVIEW

**Comment by MeroRai** [comment]
@jGauravGupta The link under Alpha Update link installer doesn't exist

**Comment by MeroRai** [comment]
@jGauravGupta Tested it locally and it all seems to work fine for me. I will wait for @dmatej's feedback as he is the resident Eclipse expert.

**Comment by jGauravGupta** [comment]
> The link under Alpha Update link installer doesn't exist
Don't worry, Eclipse IDE can recognize it.

**Comment by MeroRai** [comment]
@jGauravGupta Windows 10 Pro with Zulu JDK 1.8.0_232.

**Pull request merged**
